### ISSUE TITLE
Add downloads ie to AGMs posts

### ISSUE THREAD

**Issue by eugelogic** [eugelogic/hlcchl-gatsby#11]
CG put together a quick solution at the following
https://github.com/crgeary/hlcchl-gatsby/tree/master/static
with some inf from https://www.netlify.com/docs/headers-and-basic-auth/#custom-headers
but after trying to replicate it, when I click on the link (`<Button link="/Holly-Lodge-Community-Centre-donation-form.docx" color="white">Download Form</Button>`) it leads to the "ugly" 404 page 👎

---
Before all the above, I put together something gathered from the following documentation
https://www.gatsbyjs.org/docs/adding-images-fonts-files/#using-the-static-folder
but I had the same result as above, ie "ugly" 404 page

**Comment by IndigoEugene** [comment]
It turns out CG's method works only on live so I should push it to Netlify and see if it works.
