### ISSUE TITLE
Active Class Names

### ISSUE THREAD

**Issue by endymion1818** [eugelogic/hlcchl-gatsby#78]
You can add `activeClassName="active"` to the `<Link>` component in the nav menus so you can show the user which page they're on in the nav menu

**Comment by eugelogic** [comment]
thanks @endymion1818 how do you like it now? https://github.com/eugelogic/hlcchl-gatsby/commit/6aad90f281eb9b8e60744d725c2fd4be37732de5
https://www.hlcchl.org/
keep it coming, happy to have inputs from a Gatsby expert 😃
